version: 0.0
os: linux
files:
  - source: hello.war
    destination: /usr/share/tomcat8/webapps/
  - source: common_functions.sh
    destination: /usr/share/tomcat8/webapps/hello-scripts/common_functions.sh
  - source: deregister_from_elb.sh
    destination: /usr/share/tomcat8/webapps/hello-scripts/deregister_from_elb.sh