version: 0.0
os: linux
files:
  - source: hello.war
    destination: /usr/share/tomcat8/webapps/
hooks:
  BeforeInstall:
    - location: scripts/deregister_from_elb.sh
      timeout: 400
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
    - location: scripts/register_with_elb.sh
      timeout: 120
